server:
  port: 8080
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/gradems
    username: admin
    password: gradems
    pool:
      initial-size: 5
      max-size: 20
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
    mongodb:
      host: localhost
      port: 27017
      database: gradems